name: Test Action
on: [push]

jobs:
  get-num-square:
    runs-on: ubuntu-latest
    name: Returns the num square
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch num squared
        id: get_square
        uses: Shbak111/git_action_practice/action.yaml
        with:
          num: 11
      - name: Print the square
        run: echo "${{ steps.get_square.outputs.num_squared}}"
